[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["Josh Horwitz <joshua.d.horwitz@gmail.com>"]

[dependencies]
diesel = { version = "0.99.0", features = ["postgres"] }
diesel_infer_schema = { version = "0.99.0", features = ["postgres"] }
dotenv = "0.9.0"
